### ISSUE TITLE
Sprout hanging while quiescing when updating

### ISSUE THREAD

**Issue by tomwatson1024** [Metaswitch/sprout#1530] opened 2016-09-05 15:57 UTC
#### Symptoms

When running the commands detailed in the Chef Install section of the Upgrading a Clearwater Deployment page on clearwater.readthedocs.io to update sprout, the command occasionally seems to hang on  "\* Quiescing Sprout SIP Router sprout". It had not progressed beyond that point for around 30mins. Manually stopping the sprout service causes the command to continue running as normal. 
#### Impact

Prevents the upgrade process from completing.
#### Release and environment

A Chef deployment on Amazon EC2 of the latest commit (https://github.com/Metaswitch/sprout/commit/2705ee68b1dd6ad6be9e6a510d48337b067d4ae6) of sprout.

Diagnostics:
[20160905154619Z.ec2-54-87-239-228.compute-1.amazonaws.com.gather_diags.tar.gz](https://github.com/Metaswitch/sprout/files/455336/20160905154619Z.ec2-54-87-239-228.compute-1.amazonaws.com.gather_diags.tar.gz)
#### Steps to reproduce

The problem seems to be very intermittent. It might be possible to reproduce it by repeatedly updating sprout.

**Comment by sathiyan-sivathas** [comment] 2016-09-26 08:19
For the next person who picks this up. 

I wrote a bash script that ran `sudo service sprout quiesce` on a loop, but I couldn't reproduce the bug.  I didn't see Sprout hang once while quiescing.

**Comment by sathiyan-sivathas** [comment] 2016-09-26 16:35
I've had a look at the diags that Tom collected.  It's the last upgrade where quiescing hangs, and the are several upgrades where quiescing doesn't hang.  Looking at `/var/log/sprout/sprout_20160905T150000Z.txt`, there seem to be some interesting logs:

`05-09-2016 15:15:53.739 UTC Status main.cpp:1173: Quiesce signal received`
`05-09-2016 15:15:53.741 UTC Status stack.cpp:398: Destroyed TCP transport for port 5052`
`05-09-2016 15:15:53.741 UTC Status stack.cpp:398: Destroyed TCP transport for port 5053`
`05-09-2016 15:15:53.741 UTC Status stack.cpp:398: Destroyed TCP transport for port 5054`
`05-09-2016 15:15:53.741 UTC Status stack.cpp:398: Destroyed TCP transport for port 5055`
`05-09-2016 15:15:57.104 UTC Status memcached_config.cpp:70: Reloading memcached configuration from '/etc/clearwater/remote_cluster_settings'`
`05-09-2016 15:15:57.104 UTC Status memcached_config.cpp:109:  servers=`
`05-09-2016 15:15:57.104 UTC Status memcachedstore.cpp:430: Updating memcached store configuration`
`05-09-2016 15:15:57.104 UTC Status memcachedstore.cpp:451: Finished preparing new view, so flag that workers should switch to it`
`05-09-2016 15:15:57.104 UTC Status memcached_config.cpp:70: Reloading memcached configuration from '/etc/clearwater/cluster_settings'`
`05-09-2016 15:15:57.104 UTC Status memcached_config.cpp:109:  servers=10.0.246.255:11211`
`05-09-2016 15:15:57.104 UTC Status memcachedstore.cpp:430: Updating memcached store configuration`
`05-09-2016 15:15:57.104 UTC Status memcachedstore.cpp:451: Finished preparing new view, so flag that workers should switch to it`
`05-09-2016 15:15:57.104 UTC Status scscfselector.cpp:77: Loading S-CSCF configuration from ./s-cscf.json`
`05-09-2016 15:15:57.104 UTC Warning scscfselector.cpp:166: The S-CSCF json file is empty/invalid. Using default values`
`05-09-2016 15:15:57.104 UTC Status bgcfservice.cpp:73: Loading BGCF configuration from ./bgcf.json`
`05-09-2016 15:15:59.518 UTC Error httpclient.cpp:491: http://hs.tjw2.cw-ngv.com:8888/impu/sip%3A2010017413%40tjw2.cw-ngv.com/reg-data failed at server 10.0.104.200 : Timeout was reached (28) : fatal`
`05-09-2016 15:15:59.530 UTC Error httpclient.cpp:627: cURL failure with cURL error code 0 (see man 3 libcurl-errors) and HTTP error code 400`
`05-09-2016 15:15:59.530 UTC Error hssconnection.cpp:617: Could not get subscriber data from HSS`
`05-09-2016 15:15:59.730 UTC Error httpclient.cpp:491: http://hs.tjw2.cw-ngv.com:8888/impu/sip%3A2010004147%40tjw2.cw-ngv.com/reg-data failed at server 10.0.104.200 : Timeout was reached (28) : fatal`
`05-09-2016 15:15:59.742 UTC Error httpclient.cpp:627: cURL failure with cURL error code 0 (see man 3 libcurl-errors) and HTTP error code 400`
`05-09-2016 15:15:59.742 UTC Error hssconnection.cpp:617: Could not get subscriber data from HSS`
`05-09-2016 15:16:07.697 UTC Status alarm.cpp:62: sprout issued 1004.1 alarm`
`05-09-2016 15:16:07.697 UTC Status alarm.cpp:62: sprout issued 1001.1 alarm`
`05-09-2016 15:16:07.697 UTC Status alarm.cpp:62: sprout issued 1002.1 alarm`
`05-09-2016 15:16:07.697 UTC Status alarm.cpp:62: sprout issued 1010.1 alarm`

The HTTP errors cause us to fail to come back up and sprout produces alarm logs until `05-09-2016 15:16:07.697 UTC` when Tom presumably killed the upgrade.

**Comment by sathiyan-sivathas** [comment] 2016-10-24 14:56
I've tried at least 50 times to reproduce this and I've only hit it once.  Looking at the logs then and the logs from Tom's diags, we seem to receive a signal 1 (reload) at about the same time as the quiesce (QUIT) signal so it could be some sort of race condition.

I've tried manually sending both signals at around the same time and that still didn't repro.  I have a fix that will stop us from quiescing for eternity, so I suggest making that fix and closing this issue.

If we hit this again then we can reopen it.

**Comment by eleanor-merry** [comment] 2017-01-26 14:20
This is hopefully fixed by https://github.com/Metaswitch/pjsip-upstream/pull/56. I couldn't get any reliable repro of this, so it's hard to be confident though. I'm also going to merge the PR to stop us from quiescing for eternity to be safe.

**Closed** 2017-01-26 19:57 UTC
Labels: bug, cat:stability, critical, high-priority, major
