### ISSUE TITLE
Sprout does not fully recover from a brief overload condition.

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/sprout#1234] opened 2015-10-23 17:37 UTC
A traffic level was applied to a duplex Clearwater system which would drive a single Sprout VM to 60% CPU utilization with a 75% call / 25% re-registration mix. After running at this level for a period (error free), doubled the rate for 1 minute, then reduced the rate back to the original level. For this case the three Perimetas acting in a P-CSCF role overloaded before Clearwater and traffic recovered to an error free state once the load was reduced.

The same test was then tried with a 25% call / 75% re-registration mix to avoid the Perimeta overload. In this case Clearwater (Sprout) went into overload, but never fully recovered. After half an hour, the majority of traffic was being handled correctly, but there were still a number of 503s being generated at various points in call causing call failures on a regular basis (sometimes seeming to leading to more work that if the 503 had not been generated).

There is one question on why Clearwater overloaded at a rate that in theory it should have been able to handle. But, I'm guessing it may be due to the latency being added by the VoLTE TAS. It is also questionable whether this is a reasonable scenario given the unrealistic traffic mix. Another Perimeta needs to be added to the setup to allow overload to be induced with a more realistic mix. 

This issue is being opened as a placeholder until time permits to investigate these questions further.

**Comment by plfrancis** [comment] 2015-11-17 00:37
For 80K subscribers and a VoLTE profile (2 registrations per hour, 1.3 BHCA per subscriber), the traffic mix for a single Sprout turns out to be 45 RPS and 15 CPS. So, the 75% re-registration and 25% call mix is not as unrealistic as I initially thought (actually quite the opposite). That mix was therefore used for the following tests.

First, tried replacing the VoLTE TAS with a Sproutlet based AS to remove its latency and the problem with it directing all INVITE ACK and BYE transactions toward one Sprout node (due to a lack of SRV balancing capability). When traffic was doubled for a minute the system went into a brief overload state (10s of 503s) and recovered.

Second, tried increasing the one minute traffic spike by 10 sessions per second (7.5 re-reg, 2.5 call) to force a "deeper" overload condition. This resulted in 100s of 503s and a system that eventually recovered, but took 10s of minutes to do so. There was a restart of Chronos on both Sprout VMs and two restarts of the Sprout process itself on one of the VMs. All of these restarts were due to monit detecting 'ping' issues with these processes.

Third, tried the previous test again with the monit 'ping' job unmonitored for Chronos. This also resulted in 100s of 503s, but the system recovered to normal operation in minutes and there were no process restarts.

It may be worth investigating how liveliness checks for processes can be handled during an overload condition where latencies are above normal.

**Comment by mirw** [comment] 2015-11-17 09:53
@plfrancis, which release was this on?  @rkd-msw recently changed some of the load calculations.

**Comment by plfrancis** [comment] 2015-11-17 14:44
This was on release-82. If you think that changes in release-85 will resolve the issue I can retest once that load can run traffic (currently blocked by Metaswitch/chronos#195). Please let me know if you want the diagnostics associated with release-82, or if you prefer to wait until release-85 is stable.

**Comment by mirw** [comment] 2015-11-17 15:18
As just discussed, we'll take a look at the diags on release-82 and see if they look like they might have been fixed in release-85.

**Comment by plfrancis** [comment] 2015-11-17 15:23
Diagnostics have been uploaded for the two Chronos and two Sprout restarts (from release-82).

**Comment by mirw** [comment] 2015-11-17 17:03
The logs from Sprout show it shrinking its token bucket because the downstream Homestead is responding 504.  It appears that Sprout doesn't special-case OPTIONS polls when deciding whether or not to reject a request - it feels like maybe it should, rather than just rejecting them like everything else.

The logs from Chronos show a lot of `Adding timer to extra heap, consider re-building with a larger LONG_WHEEL_NUM_BUCKETS constant` warnings.  I think we need to enhance this log to include how far in the future these timers are, but there's no obvious reason why this would worsen performance.  Maybe it's a symptom rather than a cause?

(The Chronos logs also show a lot of `[warn] Error from accept() call: Too many open files`, but this is only after the initial crash, and is probably because we're in an odd state while we're dumping core.)

**Comment by mirw** [comment] 2015-11-17 17:06
@plfrancis, above, you mentioned that it took a very long time to recover from overload.  Is that because processes are failing or is there something else?  Do you have any diagnostics for that?

**Comment by mirw** [comment] 2015-11-17 17:06
@rkd-msw, do you have any bandwidth to look at this?

**Comment by rkd-msw** [comment] 2015-11-17 17:06
Another thought here: Chronos doesn't have overload control AFAICT. It probably should.

**Comment by rkd-msw** [comment] 2015-11-17 17:06
Yes.

**Comment by plfrancis** [comment] 2015-11-17 17:17
I believe the time to recover was extended due to the various process restarts (possibly "worsening" the overload condition). The diagnostics from IMS Bench are no longer available. If you need that information I should be able to reproduce the issue and collect them.

**Comment by rkd-msw** [comment] 2015-11-18 12:47
@plfrancis , can you confirm my understanding of the scenario below?

- Test system -  2 virtual cores, 4GB RAM
- App server invocations - invoked on REGISTER messages and both originating and terminating calls
- 45 RPS, 15 CPS - normal baseline
- 90 RPS, 30 CPS - doubled load, causes overload, but the system recovers ~immediately when load is reduced again
- 97.5 RPS, 32.5 CPS - doubled load + 10 calls, causes overload, and the system takes >20 minutes to recover when load is reduced again

**Comment by plfrancis** [comment] 2015-11-18 15:33
@rkd-msw, clarification below:

* Test system - all Clearwater nodes (duplex Sprout, Homestead, and Ralf) were using 2 virtual cores and 4GB RAM as stated
* App server invocations - exactly as stated
* 52.5 RPS, 17.5 CPS - normal baseline
* 105 RPS, 35 CPS - doubled load, results as stated
* 112.5 RPS, 37.5 CPS - doubled load + 10 new scenarios, reproduced this morning and saw similar restarts but the system recovered in just under 10 minutes, there were about half the total scenario errors seen previously (one change was made to the re-registration script so it would not simulate a REGISTER with reused credentials. this was done to avoid Metaswitch/Sprout#1261)

**Comment by rkd-msw** [comment] 2015-11-18 17:08
One more note (for myself/the future): per https://github.com/Metaswitch/chronos/issues/195#issuecomment-157745855, these tests have a one-week registration expiry time. This explains the "Adding timer to extra heap, consider re-building with a larger LONG_WHEEL_NUM_BUCKETS constant" log - timers more than an hour in the future go into the heap.

**Comment by rkd-msw** [comment] 2015-11-18 18:50
I think there are a few things we can do here.

To avoid getting into this state:

- as Matt says above, we shouldn't be blocking monit's OPTIONS polls when we're overloaded. This is particularly true if we've reduced our incoming request rate not because *our latency* is too high (which restarting us could conceivably fix), but because our upstream is overloaded.
- when Chronos dies, loads of our worker threads get blocked trying to talk to it - which will reduce their ability to pull new work off the queue, and will delay the response to Monit's OPTIONS poll. Not quite sure what the fix here is - https://github.com/Metaswitch/sprout/pull/1147/files moved Ralf requests to a pool, but we need to know the results of our Chronos requests. I've confirmed the thread exhaustion by adding a counter and a log (to a sprout with 100 worker threads):

```
18-11-2015 18:06:09.662 UTC Warning httpconnection.cpp:627: 98 threads blocked on HTTP connections
18-11-2015 18:06:09.662 UTC Warning httpconnection.cpp:627: 97 threads blocked on HTTP connections
18-11-2015 18:06:09.662 UTC Warning httpconnection.cpp:627: 96 threads blocked on HTTP connections
18-11-2015 18:06:09.663 UTC Warning httpconnection.cpp:627: 97 threads blocked on HTTP connections
18-11-2015 18:06:09.666 UTC Warning httpconnection.cpp:627: 96 threads blocked on HTTP connections
18-11-2015 18:06:09.666 UTC Warning httpconnection.cpp:627: 97 threads blocked on HTTP connections
18-11-2015 18:06:09.667 UTC Warning httpconnection.cpp:627: 95 threads blocked on HTTP connections
18-11-2015 18:06:09.670 UTC Warning httpconnection.cpp:627: 94 threads blocked on HTTP connections
18-11-2015 18:06:09.670 UTC Warning httpconnection.cpp:627: 93 threads blocked on HTTP connections
18-11-2015 18:06:09.672 UTC Warning httpconnection.cpp:627: 95 threads blocked on HTTP connections
18-11-2015 18:06:09.672 UTC Warning httpconnection.cpp:627: 94 threads blocked on HTTP connections
18-11-2015 18:06:09.673 UTC Warning httpconnection.cpp:627: 93 threads blocked on HTTP connections
18-11-2015 18:06:09.673 UTC Warning httpconnection.cpp:627: 94 threads blocked on HTTP connections
18-11-2015 18:06:09.674 UTC Warning httpconnection.cpp:627: 95 threads blocked on HTTP connections
18-11-2015 18:06:09.674 UTC Warning httpconnection.cpp:627: 95 threads blocked on HTTP connections
18-11-2015 18:06:09.675 UTC Warning httpconnection.cpp:627: 95 threads blocked on HTTP connections
```

and to improve our recovery from overload:

- we should have a more realistic request rate on initial startup (https://github.com/Metaswitch/sprout/issues/1251). Trying to reproduce this issue has given me a number (250 req/sec/core) which is a closer estimate (but still skewing low rather than high).
- could we speed up our recovery time by changing how we compress diagnostics? In particular, using a core file from one of these crashes, gzip took 18 seconds (all CPU time - no detectable waiting for IO) to compress a 2GB core to 22MB, whereas lz4 (from the liblz4-tool package) tool 1 second to compress the same core to 45MB.

(Obvious question there - why do we have a 2GB core file? Is that reflective of some kind of memory leak? I'm investigating.)

**Comment by rkd-msw** [comment] 2015-11-18 20:37
Regarding the loads-of-threads-blocked-waiting-for-Chronos issue, two possibilities:

- Chronos has no overload control, so requests to it are probably taking too long and that's using up our threads. If it had overload control (probably with a lower target latency than Sprout - 30ms?), it should start rejecting requests, rather than taking ages to process them and using up Sprout threads.
- @graemerobertson 's current work on Chronos timer IDs means that the client *could* choose the timer ID, rather than Chronos, so we don't need to wait for the response. This does mean that we can't tell, on subsequent requests, that Chronos failed to set a timer and we should try again - so this might not be the best option.

**Comment by mirw** [comment] 2015-11-18 22:15
Should we increase (or make tunable) the `LONG_WHEEL_NUM_BUCKETS` value?

**Comment by rkd-msw** [comment] 2015-11-18 22:19
Yes - probably sensible to make it tunable based on the expected length of timer (i.e. you configure that you expect week-long timers for REGISTERs and the wheels automatically sort themselves out). But I don't think that's causing any issues beyond log spam, so I'm going to look at overload tweaks first.

**Comment by rkd-msw** [comment] 2015-11-19 00:24
I've started to make and test some of the fixes above, but I'm still seeing Sprout process OPTIONS polls >1 second after they were sent, which makes Monit kill it. This happens reliably after 5-6 minutes of running 750 RPS. I'm going to try and implement a fix for https://github.com/Metaswitch/sprout/issues/1089 (not processing requests if they've been on the queue too long) and see if that improves matters.

**Comment by rkd-msw** [comment] 2015-11-19 08:59
Actually, that's unlikely to help. The logs I've added for a single OPTIONS poll show:

```
19-11-2015 08:49:22.250 UTC Status common_sip_processing.cpp:217: Skipping SAS logging for OPTIONS request
19-11-2015 08:49:22.250 UTC Status options.cpp:83: Responding to OPTIONS poll with Call-ID poll-sip-69172
```

The first is logged before it goes on the queue, the second afterwards. So it's spending 3ms on the queue - not a latency-busting amount. 

But the corresponding Monit logs are:

```
[UTC Nov 19 08:49:30] error    : 'poll_sprout_sip' SIP poll failed to 10.0.163.38:5052 with Call-ID poll-sip-69172 at 2015-11-19 08:49:21.208285565+00:00
stderr was:
Connection to 10.0.163.38 5052 port [tcp/enbd-sstatd] succeeded!
stdout was:
```

So Monit sent that poll at 08:49:21.208, a full second before Sprout saw it at 08:49:22.250 - so we were doomed however fast we processed it.

Why the 1s delay? I've run stress again with netstat and can't see a large queue building up.

**Comment by rkd-msw** [comment] 2015-11-19 10:14
I used netstat again (with the right options this time!) and saw a substantial TCP queue build up - 1200000 bytes at some points. That's 2 seconds worth of messages (1500 messages/sec at ~400 bytes each), which explains why my monit poll wasn't seen by Sprout until a second after it had been sent.

This is probably just an artifact of my overload being really high (750 RPS) to flush out any problems. I'm running again with 400 RPS, but I'll also think about TCP queue size diagnostics.

**Comment by rkd-msw** [comment] 2015-11-19 12:27
I ran at 400 RPS for 2 hours without seeing a crash, so I'll check in what I have and get it into the Slaughterhouse-5 release.

**Comment by rkd-msw** [comment] 2015-11-19 17:54
Current status:

- I've implemented overload control in Chronos - I'd expect this to improve matters, given that there's evidence monit's polling of /ping was too slow
- I've increased our default request rate on Sprout based on the results of my testing - it should now accept 500 requests/sec at start of day on a 2-core VM, alleviating the impact of crashing when under load
- I don't think there's any value in exempting OPTIONS polls from overload control - poll-sip already counts a 503 as a working liveliness check
- https://github.com/Metaswitch/clearwater-infrastructure/pull/272 moves to the faster LZ4 compression algorithm for diags, which should also alleviate the impact of restarting - but I'm going to hold off merging that while I check it's an acceptable change more widely
- I haven't made LONG_WHEEL_NUM_BUCKETS tunable
- I haven't figured out whether the 2GB core file is a problem
- I haven't investigated good TCP receive queue diagnostics

@plfrancis - I think the first two things are significant enough that it's sensible for you to retest on release-86. But if that doesn't go well, there are more improvements we could make.

**Comment by JimBunch** [comment] 2016-03-07 20:50
Marked as critical since it is call processing service affecting.

**Comment by tcaterisano** [comment] 2016-05-27 15:29
Seems to be fixed in CCV9.

**Closed by tcaterisano** 2016-05-27 15:29 UTC
Labels: bug, critical, high-priority
