### ISSUE TITLE
Call traffic impacted when a Sprout is isolated from the network

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/sprout#919] opened 2015-01-21 18:00 UTC
While running 2 CPS traffic on a duplex Clearwater configuration, Sprout-1 was isolated from the network (port disconnected from vSwitch). Calls start failing mostly with 503 Service Unavailable errors. This happens when Sprout-2 tries to use Sprout-1 as the terminating S-CSCF after an SRV lookup. The attempted TCP connection times out after 32S with a transport failure. Sprout-2 attempts to lookup another S-CSCF from Homestead, but only the local clustered record is provisioned (which was just attempted and failed) so a 503 is issued. These errors persist as long as Sprout-1 remains isolated from the network.
	
The same behaviour is also observed if Sprout-1 is simply powered off as well.

**Comment by plfrancis** [comment] 2015-01-22 16:24
It was also noticed that when Sprout-1 is reconnected to the network, the memcached service does not recover. It is left in an "unmonitored" state.

**Comment by bossmc** [comment] 2015-01-26 21:26
It looks like this is quite similar to the issues we're seeing in #920. It appears we are timing out the connection to the segregated S-CSCF in the worker thread that is being timed to calculate latency.  In this case, the expected behaviour is that we'd blacklist the address and stop using it (and retry the request to the other S-CSCF automatically before contacting the HSS for another attempt to select an S-CSCF).

Sadly, the SAS logs indicate that we're trying the bad S-CSCF every time, Sprout logs during this processing would be very useful.  The code in https://github.com/Metaswitch/sprout/blob/master/sprout/stateful_proxy.cpp#L4421 suggests we'd blacklist a server on a transport error, so I'm not sure how we're not doing that.  Level 5 logs from the I-CSCF over the time of the net-split would be super useful.

As with #920, we end up with a very small request rate in the load monitor which leads to the permanent issues after the split happens.

**Comment by AlexHockey** [comment] 2015-01-27 09:43
I would have though @plfrancis is running sproutlet proxy code. Why would we be going into https://github.com/Metaswitch/sprout/blob/master/sprout/stateful_proxy.cpp?

**Comment by bossmc** [comment] 2015-01-27 10:41
Good point, but the same code exists in https://github.com/Metaswitch/sprout/blob/master/sprout/basicproxy.cpp#L1834 which is used in the SproutletProxy.

**Comment by bossmc** [comment] 2015-01-29 19:33
The root cause here is that the first send attempt was passed to pjSIP to be put on the wire, but the TCP connection (which has vanished without trace) is completely backed up.  32 seconds later, the transaction times out and reports a send failure back to the basic proxy.  We blacklist the bad server (correct) and retry to a second server, but the `tdata` we're trying to use is still owned by the transport layer so (for safety) pjSIP rejects the second send.  Sadly this causes us to blacklist the working server (incorrect), now that both servers are blacklisted, we'll loadbalance between them, stalling half of all requests.

#925 partially resolves this, when we detect that one TCP connection is congested we'll copy the `tdata` to send the second request.  This is not a complete fix as we'll leave the old tdata in memory for an indeterminate amount of time (linux default is 20 minutes).  We'll not be adding to the memory bloat unless there's a double failure, but it would be better to flush the pending sends when the transaction gives up on them rather than letting them stagnate.

**Comment by eleanor-merry** [comment] 2015-06-09 14:14
Closing as the remaining issue here is being tracked by #1086

**Closed by eleanor-merry** 2015-06-09 14:14 UTC
Labels: cat:stability, medium-priority
