### ISSUE TITLE
SAS does not always correlate the full BYE transaction (Sprout <-> TAS) for calls with a 3rd party TAS

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/sprout#1066] opened 2015-05-29 16:16 UTC
There are two scenarios where this has been observed. The first is during traffic testing. In this case SAS seems to know about all of the NEs involved in the BYE transaction from previous interactions during the INVITE/ACK transactions, but still fails to correlate the BYE interaction between Sprout and the TAS. The second scenario is a single call with long hold time (> 32S). In this case the previous transport to the TAS is timeout and closed. A new transport is opened for the BYE transaction and SAS gets confused when trying to correlate with the previous INVITE/ACK transactions. In the latter case new headings are typically added to the ladder diagram for a call which are raw IP/Ports (vs. correlating to the associated NE name).

This is problematic for troubleshooting since a search does not give any indication that the separate Sprout/TAS fragment is available in SAS. It can only be found by examining the BYE from Perimeta to Sprout and then searching on Call-ID.

**Comment by AlexHockey** [comment] 2015-06-09 17:15
I'm pretty sure this is caused by the BYE happening more than a minute after the INVITE/ACK. This is a long-standing issue that isn't related to the TAS being present. It's also something we need help on the server side to fix. 

I propose we just close this issue, and I'll open a new one to track the larger problem (to prevent more dupes being raised). @plfrancis, does this sound OK to you?

**Comment by bossmc** [comment] 2015-07-06 15:24
@AlexHockey can you drive to triage?

**Comment by AlexHockey** [comment] 2015-07-06 15:26
I am 99% sure the problem was as I described on Jun 9. I'm going to close this issue and open one tracking the correlation window problem.

**Closed by AlexHockey** 2015-07-06 15:26 UTC
Labels: cat:diagnostics, medium-priority
