### ISSUE TITLE
Deregistration leaves subscriber registered

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#1010] opened 2015-04-17 14:03 UTC
While performing some non-clearwater tests, I've run into a flaky situation where I register a subscriber and subsequently de-register that subscriber, yet it remains registered in both homestead and the HSS. I say "flaky" because it's not consistently reproducible and it seems that the longer the clearwater system is up, the more likely this problem is to occur.

Diags have been captured.

**Comment by JimBunch** [comment] 2015-04-20 13:32
Once we hit this problem it takes a Clearwater restart to clear the problem.

**Comment by mirw** [comment] 2015-04-20 14:04
I had a look at the diagnostics.  The reason Sprout is not deregistering to Homestead or the HSS is that it thinks there are still active registrations.  Here is the memcached dump (in binary format - note that we've moved to JSON format in the latest code):

```
6     ....<urn:uuid:06ccff2f-d4d0-58f7-a6a1-15e0e66d04ec>.sip:quaff@192.168.159.206:31156;transport=TCP;ob.0gQAAC8WAAACBAAALxYAAL4saoWkSVOpJ7d3XAIRshnEafgeknGfGCdmiOupXxdD@192.168.159.184.......1U........+sip.instance."<urn:uuid:06ccff2f-d4d0-58f7-a6a1-15e0e66d04ec>".....sip:192.168.159.184:6060;transport=tcp;lr.00000000000000150a40048110120002.9999991001@os3.richlab.datcon.co.uk..os3<urn:uuid:f4594fac-01c3-537e-b94b-a8b3d066190b>.sip:quaff@192.168.159.206:25843;transport=TCP;ob.0gQAAC8WAAACBAAALxYAABlRXTSdZCVKg9jWATABB0kttt4qKNeJii4mRgdGKHor@192.168.159.184.....}.1U........+sip.instance."<urn:uuid:f4594fac-01c3-537e-b94b-a8b3d066190b>".....sip:192.168.159.184:6060;transport=tcp;lr.ffffffff8000001a0a40048110120002.9999991001@os3.richlab.datcon.co.uk..ata..
```

This essentially says that there are two registrations in the store:

*   one with identity `+sip.instance="<urn:uuid:06ccff2f-d4d0-58f7-a6a1-15e0e66d04ec>"`
*   a second with identity `+sip.instance="<urn:uuid:f4594fac-01c3-537e-b94b-a8b3d066190b>"`.

`+sip.instance="<urn:uuid:f4594fac-01c3-537e-b94b-a8b3d066190b>"` is being unregistered, but this still leaves `+sip.instance="<urn:uuid:06ccff2f-d4d0-58f7-a6a1-15e0e66d04ec>"`.  Sprout writes this back to the store.

You can see that Sprout still believes that this identity is registered because Sprout includes it on the Contact header of the REGISTER response - this header also shows that Sprout thinks there are still 190s left on that registration.

If you don't think `+sip.instance="<urn:uuid:06ccff2f-d4d0-58f7-a6a1-15e0e66d04ec>"` is registered, please can you send trace for the deregistration of that identity?  (There's nothing in any of the logs.)

It's not possible that you ran stress, stopped it and restarted it, and that some registrations from the first stress run "leaked" through to the second stress run?

Note also that I would expect this to clear as soon as the first registration expired (i.e. 190s after the logs you shared).  When you/Jim say it takes a Clearwater restart to clear the problem

*   what is the problem that you observe until Clearwater is restarted
*   which components must be restarted to clear the problem (presumably one of the data stores)?

**Comment by dtheobald** [comment] 2015-04-20 14:37
The latest example of the scenario happened this morning when I tried to make a test call on a system that had been idle since Friday (all registrations should have expired). I registered a number then made call and then tried to de-register the number which resulted in a 480 and homestead and the HSS showing it as being registered. After trying a few more calls, I did the only thing that clears the problem, which is restarting the software on all the homestead and sprout nodes.

**Comment by mirw** [comment] 2015-04-20 15:32
So are you saying that the call or the de-REGISTER gets a 480 response?  (If the latter, I'm not surprised the subscriber remains registered if so!)

Do you have trace for this failing call or de-REGISTER?  The previous trace just shows a successful de-REGISTER.

I don't believe that the *only* thing that clears the problem is restarting *all* the software on all the nodes.  Please can you check which component actually needs to be restarted to clear the problem?

**Comment by dtheobald** [comment] 2015-04-20 15:37
I should have said that the only thing that I've tried is restart all the software. Since the problem takes a significant amount of time before it occurs, I haven't narrowed down what components actually need to be restarted.

**Comment by dtheobald** [comment] 2015-04-20 15:39
I will get another SAS trace the next time it gets into that state.; which may not be until tomorrow morning.

**Comment by mirw** [comment] 2015-04-20 15:40
Thanks!  Please can you try this next time - e.g. restart Memcached only, see if this fixes the problem, if not restart Sprout (after restarting Memcached), see if that fixes the problem, etc?

On the SAS trace, is it possible to have a look at the SAS trace from this morning's run - you should be able to search by 480 responses.

**Comment by dtheobald** [comment] 2015-04-20 15:45
Yes, I will do that the next time... I found the SAS trace from this mornings 480 and add it to the diags.

**Comment by mirw** [comment] 2015-04-20 16:49
The SAS trace shows that Sprout as I-CSCF receives a de-REGISTER from the UE.  Without looking at any state, Sprout forwards this to Homestead for a `registration-status?auth-type=DEREG` query.  Again without looking at any state, Homestead turns this into a User-Authorization-Request to the HSS.  The HSS replies with an `IDENTITY_NOT_REGISTERED` error, probably because (from TS 29.228):

>   Check the state of the Public User Identity received in the request:
>   ...
>   -   If it is not registered yet, the HSS shall check the value of User-Authorization-Type received in the request:
>       -    If the value of User-Authorization-Type is DE_REGISTRATION and the Authentication pending flag is set, the HSS shall return the stored S-CSCF name and Experimental-Result-Code set to DIAMETER_SUCCESS. The HSS shall not return any S-CSCF capabilities. Otherwise, if Authentication pending flag is not set,  the HSS shall not return any S-CSCF name or S-CSCF capabilities. The HSS shall set the Experimental-Result-Code to DIAMETER_ERROR_IDENTITY_NOT_REGISTERED in the response. 

The only parts of this system that are have state are the P-CSCF (which remembers that this registration is authenticated) and the HSS (which remembers that this subscriber is not registered).

I don't think you're using Bono as P-CSCF, so please can you investigate whether it is the P-CSCF that is wrong to think the registration is still authenticated or the HSS that is wrong to think the subscriber is not registered?  (Seeing the history of the subscriber might help here.)

**Comment by dtheobald** [comment] 2015-04-22 14:10
I've added more diags from this morning's occurrence.

The scenario seemed pretty much the same:

1. Homestead/HSS agree that 9999990001 is not registered.
2. Register 9999990001
3. Homestead/HSS agree that 9999990001 is registered
4. Call 9999990001
5. Homestead/HSS disagree - HS=registered, HSS=not registered
6. Try to de-register 9999990001 results in a 480

Thus far I haven't restarted anything because it's not chronic (i.e. got 480 twice then worked).

**Comment by dtheobald** [comment] 2015-04-22 14:21
The one thing I found in the log file that looked suspicious was this:
```
22-04-2015 13:47:45.545 UTC Debug memcachedstore.cpp:540: Writing 174 bytes to table av key 9999990001@os3.richlab.datcon.co.uk\7f9fefbe6db77e12, CAS = 17186, expiry = 40
22-04-2015 13:47:45.545 UTC Debug memcachedstore.cpp:193: Key av\\9999990001@os3.richlab.datcon.co.uk\7f9fefbe6db77e12 hashes to vbucket 89 via hash 0xbf793fd9
22-04-2015 13:47:45.545 UTC Debug memcachedstore.cpp:560: 2 write replicas for key av\\9999990001@os3.richlab.datcon.co.uk\7f9fefbe6db77e12
22-04-2015 13:47:45.545 UTC Debug memcachedstore.cpp:614: Attempt conditional write to vbucket 89 on replica 0 (connection 0x7f464c0666c0), CAS = 17186, expiry = 40
22-04-2015 13:47:45.546 UTC Debug memcachedstore.cpp:649: memcached_cas command failed, rc = 12 (CONNECTION DATA EXISTS)
SUCCESS
22-04-2015 13:47:45.546 UTC Info memcachedstore.cpp:671: Contention writing data for av\\9999990001@os3.richlab.datcon.co.uk\7f9fefbe6db77e12 to store
22-04-2015 13:47:45.546 UTC Error avstore.cpp:71: Failed to write Authentication Vector for private_id 9999990001@os3.richlab.datcon.co.uk
22-04-2015 13:47:45.546 UTC Error authentication.cpp:558: Tried to tombstone AV for 9999990001@os3.richlab.datcon.co.uk/7f9fefbe6db77e12 after processing an authentication, but failed

```

**Comment by mirw** [comment] 2015-04-22 14:36
Thanks for pointing out that log - this is indeed the problem.

When we receive an unauthenticated REGISTER, we challenge it and write the challenge to memcached.  We then start a timer to time out the challenge (and tell the HSS) if it takes too long.

When we receive the successfully-authenticated REGISTER, we delete the entry from memcached, meaning that when the timer pops, we don't tell the HSS.  However, this deletion (or rather tombstone-writing) fails.

**Comment by mirw** [comment] 2015-04-22 14:39
We need to investigate why the memcached write is failing.

I'm also slightly worried that whenever a user tries to register for the same identity and this times out, we'll unregister any existing registrations too.

**Comment by mirw** [comment] 2015-04-22 14:46
It sounds like we could cancel the Chronos timer at the point that we successfully authenticate, which might help here.

**Comment by mirw** [comment] 2015-04-22 15:08
On my worry about a user trying to register for the same identity, this timing out and us unregistering any existing registrations, we're OK because the HSS should handle this.  From TS 29.298, talking about the Server-Assignment-Type field in the Server-Assignment-Request:

> If it indicates AUTHENTICATION_FAILURE (e.g. there is a mismatch in IP-address secure binding information) or AUTHENTICATION_TIMEOUT (e.g. no response to Digest challenge), the HSS shall keep the registration state of the Public User Identity. The HSS shall check the registration state for the Public User Identity in the request and only if the registration state of the Public User Identity is Not Registered, the HSS shall clear the S-CSCF name associated with the Public User Identity.
>
> If the Public User Identity’s authentication pending flag which is specific for the Private User Identity is set, the HSS shall clear it. The Result-Code shall be set to DIAMETER_SUCCESS.

In summary, if the subscriber is already registered, they should stay registered.

**Comment by mirw** [comment] 2015-04-22 15:47
The reason that the memcached write fails with contention is that the connection to memcached instance 1 was failed when we tried to read, so we read from memcached instance 2 instead.  By the time we tried to write back, memcached instance 1 was alive again, and so we tried to CAS to that.  Memcached instance 1 had a different CAS value (as CAS values are not transferrable between servers) so this write failed.  I think the immediate fix is to do the usual retry behavior on contention, but we should probably also look at improving handling of this specific memcached failure mode.

**Comment by mirw** [comment] 2015-04-22 16:09
OK, so it looks like the changes are

*   https://github.com/Metaswitch/sprout/blob/dev/sprout/authentication.cpp#L612 - loop while writing to AV store fails (with a finite number of loops)
*   https://github.com/Metaswitch/sprout/blob/dev/sprout/authentication.cpp#L612 - cancel the Chronos timer
*   https://github.com/Metaswitch/sprout/blob/dev/sprout/authentication.cpp#L416 - either loop here trying to set the AV or (possibly better) return a negative response code if we can't write to the AV store.

**Comment by mirw** [comment] 2015-04-27 15:29
Actually, the third bullet isn't necessary - returning 200 OK with an invalid challenge in this race condition will just mean that the challenge response will return stale (which is basically true), and we'll retry at that point.

**Comment by mirw** [comment] 2015-04-27 15:31
I'm going to fork the second bullet into a separate issue.  It's not actually required for this fix, and it's non-trivial to fix (because we need to write the Chronos timer ID into memcached so that we can cancel it when authentication succeeds, but we want to write the AV into memcached first so that if it fails we don't have to cancel the timer).

**Comment by mirw** [comment] 2015-04-27 15:35
I've raised #1019 to cover the second bullet.

This issue just covers the first bullet.  I have a fix for this, which I'm just testing.

**Closed** 2015-05-11 10:54 UTC
Labels: high-priority
