### ISSUE TITLE
calls fail with mixed versions of sprout

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sprout#1394] opened 2016-04-12 19:29 UTC
#### Symptoms

During an upgrade from release-82 to release-94 when in a configuration where one sprout was running release-82 and the other sprout was running release-94, I get spurious call failures (480 temporarily unavailable) even though the UE has registered.

#### Impact

Calls fail.

#### Release and environment 

Mix of release-82 and release-94 sprout nodes

#### Steps to reproduce
1) Add ```impi_store_mode=av-impi``` to shared_config and distribute.
2) Upgrade homestead nodes to release-94
3) Upgrade one sprout node to release-94
4) Register a couple of UEs and make calls between them. Invariably a call will fail with 480.

Diags are available (sprout-1 is running release-94)

**Comment by mirw** [comment] 2016-04-12 19:47
@dtheobald, I can't see a SAS trace for the failed call.  Your 480call.sas file actually contains a REGISTER.  Please can you check and point me to the correct diagnostics?

**Comment by johadalin** [comment] 2016-04-12 20:09
I've put a couple of traces up with the diags from earlier failures Doug sent to me.

**Comment by mirw** [comment] 2016-04-13 10:12
I've looked at the SAS trace.  The failure appears to be that Homestead sends a Location-Information-Request and gets back a valid but empty Location-Information-Answer.  This suggests that the HSS believes that the subscriber is unregistered.

This looks like a very similar problem to https://github.com/Metaswitch/homestead/issues/325 - in that case, a UAR was rejected because the subscriber was unregistered, despite us believing the subscriber to have been successfully registered.

Either the HSS is randomly dropping registrations, or something else is requesting it to clear them out.  Getting **all** the SAS traces for this subscriber around the time of the failure would show whether something is requesting to clear them out, but an alternative would be to run a test with network capture on the HSS, filtering on TCP port 3868.

@dtheobald, please can you gather these diagnostics?

**Comment by mirw** [comment] 2016-04-13 10:13
Marking as critical on the basis that this might be a Clearwater bug.  If it's an HSS bug, it's clearly not.

**Comment by dtheobald** [comment] 2016-04-13 10:56
I've updated 480call.sas to contain the correct trace. I've left MY SAS running, so you can also see the complete set of traces by opening the link.

**Comment by mirw** [comment] 2016-04-13 11:31
OK, so we now have the full picture, and there are two issues here.

*   The UE sends a REGISTER to Sprout.  The uplevel sprout creates a challenge, stories both IMPI and AV entries, and sends it back.  It also sets a Chronos timeout to timeout the authentication.
*   The UE now sends a response to the challenge.  The downlevel sprout checks the challenge and tombstones the AV entry (but not the IMPI).  It doesn't cancel the Chronos timeout, because the AV entry has been tombstoned anyway.
*   (Some calls happen.)
*   The Chronos timeout pops and hits the uplevel Sprout.  The uplevel Sprout looks up the IMPI (which it finds) and the AV (which it finds, but tombstoned, so it throws it away), combines them, resulting by taking the IMPI result, and decides that authentication has timed out.  It then believes the authentication has failed, and times it out.

The fix is to be smarter when combining IMPI and AV results.

The second issue is that SAS correlation is broken between versions because in the uplevel version we store the "branch" JSON field inside the "digest" object, whereas the downlevel version stores it in the root object.

This is the same issue as Metaswitch/homestead#325.  Since we've done the analysis here, I'm going to suggest we close that as a duplicate.

**Comment by mirw** [comment] 2016-04-13 18:53
@JimBunch, I have a fix for this (#1398).  I'm pretty confident in this, and it's reasonably self-contained, so I think it should be merged - please can you confirm?

**Comment by JimBunch** [comment] 2016-04-13 19:02
Confirmed.

**Comment by mirw** [comment] 2016-04-14 14:45
@dtheobald, I've committed the fix to this issue.  Please can you re-test with this fix?

As well as the stress scenario, please can you also check that the REGISTER/401/REGISTER/200 flow all appears in a single SAS trace when running with a mixed version Sprout cluster?  Thanks!

**Closed** 2016-04-29 16:45 UTC
Labels: bug, critical, high-priority
