### ISSUE TITLE
Bono doesn't support access/core network separation

### ISSUE THREAD

**Issue by mirw** [Metaswitch/sprout#996] opened 2015-04-08 17:29 UTC
Bono doesn't support having access traffic and core traffic on separate networks.  It might be useful to do so.

It doesn't look too hard to do this.  The fill_transport_details function always gets the local address (by calling pj_getaddrinfo on local_host), and we could tweak this to optionally use the public address instead.

Note that Bono still wouldn't support media, so an SBC would be required to bridge media between the access and core networks.

**Comment by rkd-msw** [comment] 2015-04-10 10:57
Duplicate of https://github.com/Metaswitch/sprout/issues/364?

**Comment by mirw** [comment] 2015-04-10 11:41
Agreed.

**Closed** 2015-04-10 11:41 UTC
Labels: cat:enhancement, duplicate, medium-priority
